baseURL = "http://www.lunzi.space/"
languageCode = "en-us"
title = "KylinJiang's blog"
theme = "solar-theme-hugo"
paginate = 5
publishDir = "docs"

pygmentsStyle = "solarized-dark" # solarized-light, -dark or -dark256
copyright = "Copyright Â© 2019 KylinJiang. All Rights Reserve"

[params]
  scheme = "preference" # light, dark, gray or preference
  description = "This what i live for"

[menu]
  [[menu.main]]
    name = "Feed"
    url = "/index.xml"
